services:
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
  api:
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    environment:
      - FLASK_DEBUG=1
